#!/bin/bash


while :
do


clear


echo "Team:"
echo
echo "-> XMasterNinni (Owner)"
echo "-> Dazozzo"
echo "-> muhahahaah"
echo "-> tilal6991"
echo
echo "Credits:"
echo
echo "-> dsixda for helping me in Bash/Shell Scripting"
echo "-> KonstaT for giving me some tips in porting" 
echo
echo "x = Exit"




while : enterLetter != "x"
	do
	
	read enterLetter

  	if [ "$enterLetter" == "x" ]
 	 then
		exit 0
  	else 
    echo "Invalid option"
 	 fi

done


done

