#!/bin/bash

clear

while :
do

  clear

echo "-------------------Porting Process---------------------------"


#system/framework
echo "Copying files...<framework>"
sudo cp -r port_rom/system/framework base_rom/system

#system/app
echo "Copying files...<app>"
cp -r port_rom/system/app base_rom/system

#system/media
echo "Copying files...<media>" 
cp port_rom/system/media/*.zip base_rom/system/media
echo "Copying files...<audio>" 
cp -r port_rom/system/media/audio base_rom/system/media

#Finish
echo "Finished copying!"
echo
echo
echo
echo
echo
echo
echo
echo "Zipping <port_rom>"

cd port_rom
zip -r Port.zip META-INF system boot.img

echo
echo "Your zip is here: /port_rom/Port.zip"
echo "Just flash the zip in a recovery."
echo 
echo "To finish, close the terminal now."

read enterLetter

  if [ "$enterLetter" == "x" ]
  then
    scripts/change_device
    
    if [ "$?" == "1" ]
    then
      continue
    fi

  elif [ "$enterLetter" == "x" ]
  then
    scripts/change_device
  else 
    echo "Invalid option"
    continue
  fi

  scripts/press_enter

done
