#!/bin/bash

clear

while :
do

  clear


  echo "placeholder"
  echo "  x = Exit"
  echo 
  echo -n "// "

   read enterLetter

  if [ "$enterLetter" == "a" ]
  then
 

    
    if [ "$?" == "1" ]
    then
      continue
    fi

  elif [ "$enterLetter" == "e" ]
  then
    #placeholder
  elif [ "$enterLetter" == "x" ]
  then
    exit 0
  else 
    echo "Invalid option"
    continue
  fi

  scripts/press_enter

done

